tst_mcs: [16, 64, 128]

_optim:
  - name: Adam
    args:
      lr: 0.1
      amsgrad: yes
  - name: Adam
    args:
      lr: 0.05
      amsgrad: yes
  - name: Rprop
    args:
      lr: 0.1
  - name: Rprop
    args:
      lr: 0.05
  - name: RMSprop
    args:
      lr: 0.1
      momentum: 0.5
  - name: RMSprop
    args:
      lr: 0.05
      momentum: 0.5
  - name: RMSprop
    args:
      lr: 0.05
      momentum: 0.5
