experiment: bnn-cifar10-dev

mode: SVI
trn_mcs: 1
tst_mcs: 64

warmup:
  epochs: 2
  split: 0.5
  reset_optim: yes

epochs: 2
# batch_size: &batch_size 128

optim:
  name: Adam
  args:
    lr: 0.005
    amsgrad: yes

trn_loader:
  batch_size: 128
  shuffle: yes
  num_workers: 2
  pin_memory: yes
val_loader:
  batch_size: 1024
  shuffle: yes
  num_workers: 2
  pin_memory: yes

