experiment: bnn-cifar10-dev

mode: SVI
trn_mcs: 1
tst_mcs: 64

# warmup:
#   epochs: 2
#   split: 0.5
#   reset_optim: yes

epochs: 4
# batch_size: &batch_size 128

optim:
  name: Adam
  args:
    lr: 0.005
    amsgrad: yes

trn_loader:
  batch_size: 128
  shuffle: yes
  num_workers: 2
  pin_memory: yes
val_loader:
  batch_size: 1000
  shuffle: no
  num_workers: 2
  pin_memory: yes

log:
  detailed: no
  mle_ish: yes
  train_no_aug: yes